=== silverirakesh/Assignment/automation-framework/target/classes/extent-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="extentreports">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="configuration">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="theme" type="xs:string" />
							<xs:element name="encoding" type="xs:string" />
							<xs:element name="documentTitle" type="xs:string" />
							<xs:element name="reportName" type="xs:string" />
							<xs:element name="protocol" type="xs:string" />
							<xs:element name="timeStampFormat" type="xs:string" />
							<xs:element name="chartVisibilityOnOpen" type="xs:string" />
							<xs:element name="level" type="xs:string" />
							<xs:element name="offlineMode" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== silverirakesh/Assignment/automation-framework/src/main/resources/extent-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<extentreports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="extent-config.xsd">
    <configuration>
        <!-- Report Theme -->
        <theme>standard</theme>

        <!-- Encoding -->
        <encoding>UTF-8</encoding>

        <!-- Document Title -->
        <documentTitle>Test Automation Report</documentTitle>

        <!-- Report Name -->
        <reportName>Extent Report - Selenium Test Execution</reportName>

        <!-- Report Visibility -->
        <protocol>https</protocol>

        <!-- Timestamp Format -->
        <timeStampFormat>yyyy-MM-dd HH:mm:ss</timeStampFormat>

        <!-- Enable or Disable Chart -->
        <chartVisibilityOnOpen>true</chartVisibilityOnOpen>

        <!-- Log Level -->
        <level>INFO</level>

        <!-- Enable Offline Mode (No Internet Dependency) -->
        <offlineMode>true</offlineMode>
    </configuration>
</extentreports>
